version: '3.6'

services:

  stage_viewer_webpack_dev_server:
    build:
      context: ./
      dockerfile: npm_run.dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./:/stageViewer:ro
      - /stageViewer/node_modules  # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - ./static:/stageViewer/static:rw
    links:
      - stage_orchestration
    command: npm run start

  # docker-compose run --rm npm_run
  # Creates static files in ./static/
  npm_run:
    build:
      context: ./
      dockerfile: npm_run.dockerfile
    volumes:
      - ./:/stageViewer:ro
      - /stageViewer/node_modules  # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - ./static:/stageViewer/static:rw
    command: build
